### PR TITLE
Include argument types

### PR DESCRIPTION
**Pull request by guil95**

### CODE REVIEW

**Comment by mattiasgeniar** [comment]
Hi @guil95 ! 

Mixed feelings about this PR, I'd love for PHP to introduce the mixed arguments so it could be `int|float`. 

Reason I didn't typehint the arguments is that it _works_ with both integers & floats, I only mandate the return types. I think I'll change this so validate the variables types inside the function itself, until PHP has support for multiple argument types.

**Comment by jdreesen** [comment]
> Mixed feelings about this PR, I'd love for PHP to introduce the mixed arguments so it could be `int|float`.

Fortunately, union types come in PHP 8 :)
https://wiki.php.net/rfc/union_types_v2

**Comment by guil95** [comment]
I don't agree with that, because I can define a method as float and the method accepts numbers without a floating point. If I leave the mixed type, it will open a gap for the passage of any type, its library is very good.

**Comment by mattiasgeniar** [comment]
> I don't agree with that, because I can define a method as float and the method accepts numbers without a floating point. If I leave the mixed type, it will open a gap for the passage of any type, its library is very good.

You are right, I was (wrongfully) under the assumption that a float as input type in the function would require an explicit casting to float beforehand, but that's not the case.

In that case: this is perfect! :-) 

Thank you for the PR!

**Pull request merged**
